# Generated by Django 4.0.1 on 2022-02-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegisterModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Enter UserName', max_length=100)),
                ('mobile', models.IntegerField(help_text='Enter Mobile Number')),
                ('email', models.EmailField(help_text='Enter Email', max_length=100)),
                ('password', models.CharField(help_text='Enter Password', max_length=100)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
