# Generated by Django 4.0.1 on 2022-02-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('bid_id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(help_text='Enter Username', max_length=100)),
                ('asset_name', models.CharField(help_text='Enter Asset Name', max_length=100)),
                ('bid_starting_price', models.IntegerField()),
                ('bid_price', models.IntegerField()),
                ('bid_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bid_details',
            },
        ),
    ]
