# Generated by Django 4.0.1 on 2022-02-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_bidding'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='status',
            field=models.CharField(default='pending', max_length=100, null=True),
        ),
    ]
