# Generated by Django 4.0.1 on 2022-02-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_bidding_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistermodel',
            name='status',
            field=models.CharField(default='pending', max_length=100, null=True),
        ),
    ]
