# Generated by Django 4.0.1 on 2022-03-26 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_userregistermodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidding',
            name='user_id',
        ),
        migrations.AddField(
            model_name='bidding',
            name='user_register_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userapp.userregistermodel'),
        ),
    ]
