# Generated by Django 4.0.1 on 2022-03-26 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_remove_bidding_user_id_bidding_user_register_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='user_register_model',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='userapp.userregistermodel'),
        ),
    ]
