# Generated by Django 4.0.1 on 2022-03-30 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_assetsmodel_posted_date'),
        ('userapp', '0006_alter_bidding_user_register_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidding',
            name='asset_id',
        ),
        migrations.AddField(
            model_name='bidding',
            name='assets_model',
            field=models.ForeignKey(db_column='asset_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.assetsmodel'),
        ),
        migrations.AddField(
            model_name='userregistermodel',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
