# Generated by Django 4.0.1 on 2022-03-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_remove_bidding_asset_id_bidding_assets_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistermodel',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
