# Generated by Django 4.0.1 on 2022-03-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_alter_userregistermodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistermodel',
            name='mobile',
            field=models.BigIntegerField(help_text='Enter Mobile Number'),
        ),
    ]
