# Generated by Django 4.0.1 on 2022-03-30 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_assetsmodel_posted_date'),
        ('userapp', '0011_alter_bidding_bid_starting_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='assets_model',
            field=models.ForeignKey(db_column='asset_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='adminapp.assetsmodel'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='user_register_model',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='register', to='userapp.userregistermodel'),
        ),
    ]
