# Generated by Django 4.0.1 on 2022-03-30 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_alter_bidding_assets_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidding',
            old_name='assets_model',
            new_name='asset',
        ),
        migrations.RenameField(
            model_name='bidding',
            old_name='user_register_model',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='bidding',
            name='asset_name',
        ),
        migrations.RemoveField(
            model_name='bidding',
            name='bid_starting_price',
        ),
        migrations.RemoveField(
            model_name='bidding',
            name='user_name',
        ),
    ]
