# Generated by Django 4.0.1 on 2022-04-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_rename_assets_model_bidding_asset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistermodel',
            name='status',
        ),
    ]
