# Generated by Django 4.0.1 on 2022-02-05 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_assetsmodel_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsmodel',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 5, 16, 18, 36, 893268)),
        ),
    ]
