# Generated by Django 4.0.1 on 2022-03-30 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_assetsmodel_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsmodel',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 15, 45, 32, 118949)),
        ),
    ]
