# Generated by Django 4.0.1 on 2022-04-01 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_assetsmodel_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsmodel',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 1, 20, 15, 56, 964839)),
        ),
    ]
